let
    Source = #"rack_breakdown (Source)",
    #"Removed Top Rows" = Table.Skip(Source,35),
    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
    #"Renamed Columns: DC>Site" = Table.RenameColumns(#"Promoted Headers",{{"Data Center", "Site"}}),
    #"Duplicated Column: POD Code" = Table.DuplicateColumn(#"Renamed Columns: DC>Site", "POD Code", "POD Code - Copy"),
    #"Reordered Columns" = Table.ReorderColumns(#"Duplicated Column: POD Code",{"Site", "Server Room", "POD Code - Copy", "Pod", "Speed", "Path", "Group", "Type", "Sub-Type", "Status", "Max Slots", "Rack ID", "kW/Rack", "Utility Identifier", "Lease Identifier", "Zone-Power", "Row Number", "Notes", "Column20", "Active Servers", "Active Hardware", "Current Inventory", "Current Spare Pool", "Adjusted Inventory", "Current Other", "Total Servers", "Total Hardware", "Adj Max Slots", "Active Slots", "Inventory Slots", "Other Slots", "Used Slots", "Spare Pool Slots", "Usable Slots", "Unused Slots", "Unused + Inventory", "Unused + Inv + Other", "Unusable Slots", "Avg kW per Slot:", "Reserved Power", "Spare Pool Power", "Type - Status", "Empty Flag", "POD Code", "G", "H", "J", "K", "Total", "kW per Active Slot", "Est. Total Rack kW", "Power Strip Errors", "Est kW Remaining", "Est. Slots Remaining", "Start/End Rack ID", "Empty Rack Count", "Empty Row Flag", "Row Path"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns",{"Pod"}),
    #"Renamed Columns: POD Code Copy>POD" = Table.RenameColumns(#"Removed Columns1",{{"POD Code - Copy", "POD"}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Renamed Columns: POD Code Copy>POD",{"Site", "Server Room", "POD", "Speed", "Path", "Group", "Type", "Sub-Type", "Status", "Max Slots", "kW/Rack", "Rack ID", "Utility Identifier", "Lease Identifier", "Zone-Power", "Row Number", "Notes", "Column20", "Active Servers", "Active Hardware", "Current Inventory", "Current Spare Pool", "Adjusted Inventory", "Current Other", "Total Servers", "Total Hardware", "Adj Max Slots", "Active Slots", "Inventory Slots", "Other Slots", "Used Slots", "Spare Pool Slots", "Usable Slots", "Unused Slots", "Unused + Inventory", "Unused + Inv + Other", "Unusable Slots", "Avg kW per Slot:", "Reserved Power", "Spare Pool Power", "Type - Status", "Empty Flag", "POD Code", "G", "H", "J", "K", "Total", "kW per Active Slot", "Est. Total Rack kW", "Power Strip Errors", "Est kW Remaining", "Est. Slots Remaining", "Start/End Rack ID", "Empty Rack Count", "Empty Row Flag"}),
    #"Inserted Merged Column" = Table.AddColumn(#"Reordered Columns1", "Merged", each Text.Combine({[Site], Text.PadStart( Text.From([Server Room], "en-US"), 2, "0")}, ".SR")),
    #"Reordered Columns2" = Table.ReorderColumns(#"Inserted Merged Column",{"Site", "Merged", "Server Room", "POD", "Speed", "Path", "Group", "Type", "Sub-Type", "Status", "Max Slots", "kW/Rack", "Rack ID", "Utility Identifier", "Lease Identifier", "Zone-Power", "Row Number", "Notes", "Column20", "Active Servers", "Active Hardware", "Current Inventory", "Current Spare Pool", "Adjusted Inventory", "Current Other", "Total Servers", "Total Hardware", "Adj Max Slots", "Active Slots", "Inventory Slots", "Other Slots", "Used Slots", "Spare Pool Slots", "Usable Slots", "Unused Slots", "Unused + Inventory", "Unused + Inv + Other", "Unusable Slots", "Avg kW per Slot:", "Reserved Power", "Spare Pool Power", "Type - Status", "Empty Flag", "POD Code", "G", "H", "J", "K", "Total", "kW per Active Slot", "Est. Total Rack kW", "Power Strip Errors", "Est kW Remaining", "Est. Slots Remaining", "Start/End Rack ID", "Empty Rack Count", "Empty Row Flag", "Row Path"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Reordered Columns2",{"Server Room"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns2",{{"Merged", "Server Room"}}),
    #"Removed Columns3" = Table.RemoveColumns(#"Renamed Columns",{"Column20", "Adjusted Inventory", "Current Other"}),
    #"Reordered Columns3" = Table.ReorderColumns(#"Removed Columns3",{"Site", "Server Room", "POD", "Speed", "Path", "Group", "Type", "Sub-Type", "Status", "Adj Max Slots", "Max Slots", "kW/Rack", "Rack ID", "Utility Identifier", "Lease Identifier", "Zone-Power", "Row Number", "Notes", "Active Servers", "Active Hardware", "Current Inventory", "Current Spare Pool", "Total Servers", "Total Hardware", "Active Slots", "Inventory Slots", "Other Slots", "Used Slots", "Spare Pool Slots", "Usable Slots", "Unused Slots", "Unused + Inventory", "Unused + Inv + Other", "Unusable Slots", "Avg kW per Slot:", "Reserved Power", "Spare Pool Power", "Type - Status", "Empty Flag", "POD Code", "G", "H", "J", "K", "Total", "kW per Active Slot", "Est. Total Rack kW", "Power Strip Errors", "Est kW Remaining", "Est. Slots Remaining", "Start/End Rack ID", "Empty Rack Count", "Empty Row Flag"}),
    #"Removed Columns4" = Table.RemoveColumns(#"Reordered Columns3",{"Max Slots"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns4",{{"Adj Max Slots", "Max Slots"}}),
    #"Reordered Columns4" = Table.ReorderColumns(#"Renamed Columns1",{"Site", "Server Room", "POD", "Speed", "Path", "Group", "Type", "Sub-Type", "Status", "Max Slots", "kW/Rack", "Rack ID", "Utility Identifier", "Lease Identifier", "Zone-Power", "Row Number", "Notes", "Active Servers", "Active Hardware", "Current Inventory", "Current Spare Pool", "Total Servers", "Total Hardware", "Active Slots", "Inventory Slots", "Other Slots", "Used Slots", "Spare Pool Slots", "Usable Slots", "Unused Slots", "Unused + Inventory", "Unused + Inv + Other", "Unusable Slots", "Avg kW per Slot:", "Reserved Power", "Spare Pool Power", "Type - Status", "Empty Flag", "Rack", "POD Code", "G", "H", "J", "K", "Total", "kW per Active Slot", "Power Strip Errors", "Est. Slots Remaining", "Start/End Rack ID", "Empty Rack Count", "Empty Row Flag"}),
    #"Removed Columns5" = Table.RemoveColumns(#"Reordered Columns4",{"Usable Slots", "Unused Slots", "Unused + Inventory", "Unused + Inv + Other", "Unusable Slots", "Avg kW per Slot:", "Reserved Power", "Spare Pool Power", "Type - Status", "Empty Flag", "kW per Active Slot", "Power Strip Errors", "Est. Total Rack kW", "Est kW Remaining", "Est. Slots Remaining", "Empty Rack Count", "Empty Row Flag"}),
    #"Added Custom" = Table.AddColumn(#"Removed Columns5", "Est kW Usage", each List.Max({[Total]}&{[Power Calculator]})),
    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"Total", "Power Calculator"}),
    #"Reordered Columns5" = Table.ReorderColumns(#"Removed Columns",{"Rack Path", "Site", "Server Room", "POD", "Speed", "Path", "Group", "Type", "Sub-Type", "Status", "Max Slots", "kW/Rack", "Rack ID", "Utility Identifier", "Lease Identifier", "Zone-Power", "Row Number", "Notes", "Active Servers", "Active Hardware", "Current Inventory", "Current Spare Pool", "Total Servers", "Total Hardware", "Active Slots", "Inventory Slots", "Other Slots", "Used Slots", "Spare Pool Slots", "Rack", "POD Code", "G", "H", "J", "K", "Est kW Usage", "Start/End Rack ID", "Row Path"}),
    #"Filtered Rows" = Table.SelectRows(#"Reordered Columns5", each not Text.Contains([POD], "Unknown")),
    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"Rack Path"}, #"DCIM Data", {"RackName"}, "DCIM Data", JoinKind.LeftOuter),
    #"Expanded DCIM Data" = Table.ExpandTableColumn(#"Merged Queries", "DCIM Data", {"MaxW"}, {"MaxW"}),
    #"Added Custom1" = Table.AddColumn(#"Expanded DCIM Data", "kW Compare", each List.Max({[MaxW] / 1000}&{[Est kW Usage]})),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Est kW Usage-NEW", each if [kW Compare] = 0 and 
( [Status] = "Live" or [Status] = "Power Limit" or [Status] = "Decom" or [Status] = "Migrations" )
then [#"kW/Rack"] else [kW Compare]),
    #"Reordered Columns6" = Table.ReorderColumns(#"Added Custom2",{"Rack Path", "Site", "Server Room", "POD", "Speed", "Path", "Group", "Type", "Sub-Type", "Status", "Max Slots", "kW/Rack", "Rack ID", "Utility Identifier", "Lease Identifier", "Zone-Power", "Row Number", "Notes", "Active Servers", "Active Hardware", "Current Inventory", "Current Spare Pool", "Total Servers", "Total Hardware", "Active Slots", "Inventory Slots", "Other Slots", "Used Slots", "Spare Pool Slots", "Rack", "POD Code", "G", "H", "J", "K", "Est kW Usage-NEW", "Est kW Usage", "Start/End Rack ID", "MaxW", "kW Compare"}),
    #"Removed Columns6" = Table.RemoveColumns(#"Reordered Columns6",{"Est kW Usage", "MaxW", "kW Compare"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns6",{{"Est kW Usage-NEW", "Est kW Usage"}})
in
    #"Renamed Columns2"
